name: build-linux-amd64-wheels
'on':
  workflow_dispatch:
    inputs:
      packages:
        type: string
        description: Pkgs to build (comma-separated, empty for all)
        required: false
      graalpy_url:
        type: string
        description: GraalPy download url
        required: true
jobs:
  build_wheels:
    runs-on:
      - ubuntu-latest
    container: 
      image: quay.io/pypa/manylinux_2_28_x86_64
      options: --cpus 4 # 增加CPU资源
    env:
      PACKAGES_TO_BUILD: ${{ inputs.packages }}
      SCIPY_USE_PYTHRAN: "0"  # 在这里全局设置
    steps:
      - name: Install dependencies
        run: |
          dnf install -y epel-release
          crb enable
          dnf makecache --refresh
          dnf module install -y nodejs:18
          dnf install -y /usr/bin/patch
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings -A unexpected-cfgs -A unused-macros -A static-mut-refs -A unused-variables -A unused-imports"
          cache: false
      - name: 安装lxml依赖
        run: dnf install -y libxml2-devel libxslt-devel
      - name: Install system build dependencies (dnf)
        run: |
          # 如果需要 epel（ninja 在 epel 可用），先尝试启用
          dnf -y install epel-release
          dnf -y update
          # 对于 AlmaLinux，启用 powertools 而不是 crb
          dnf -y install dnf-plugins-core
          dnf -y config-manager --set-enabled powertools || dnf -y config-manager --set-enabled crb || echo "无法启用 powertools/crb，继续执行"
          # 安装开发工具组
          dnf -y groupinstall "Development Tools"
          # 安装基础编译工具和依赖
          dnf -y install \
            gcc gcc-c++ gcc-gfortran make cmake pkgconfig git\
            python3-devel python3-pip python3-virtualenv \
            openblas-devel lapack-devel blas-devel\
            libgcrypt-devel libgpg-error-devel \
            libxml2-devel libxslt-devel xz-devel \
            ninja-build libjpeg-turbo-devel zlib-devel libpng-devel  
      
      - name: Pre-install Python build-time tools
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          # meson/ninja/pythran/pybind11 在 SciPy 构建阶段必须可用
          python3 -m pip install meson ninja pythran pybind11

      - name: Install Rust toolchain (actions-rs)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Set environment for faster builds
        run: |
          # 限制并行度,避免内存溢出
          echo "NPY_NUM_BUILD_JOBS=2" >> $GITHUB_ENV
          echo "SCIPY_NUM_BUILD_JOBS=2" >> $GITHUB_ENV
          # 使用更快的链接器
          echo "LDFLAGS=-fuse-ld=gold" >> $GITHUB_ENV
      - name: Build wheels
        env:
            SCIPY_USE_PYTHRAN: "0"  # 步骤级别再次确认
        run: |
          # Shell 级别再次设置
          export SCIPY_USE_PYTHRAN=0
          # 验证环境变量
          echo "SCIPY_USE_PYTHRAN = $SCIPY_USE_PYTHRAN"
          python3 -m venv wheelbuilder_venv
          #使用依赖约束
          export PIP_CONSTRAINT="${PWD}/constraints.txt"
          # 确保虚拟环境中也使用预编译的 NumPy
          wheelbuilder_venv/bin/python3 -m pip install --only-binary=:all: numpy
          wheelbuilder_venv/bin/python3 scripts/wheelbuilder/build_wheels.py ${{ inputs.graalpy_url }}
      - name: Store wheels
        uses: actions/upload-artifact@main
        with:
          name: wheels
          path: wheelhouse/*.whl
          if-no-files-found: error
